### ISSUE TITLE
HUION 1060PRO+  parameters

### ISSUE THREAD

**Issue by LHT-01** [joseluis/huion-linux-drivers#4]
Hello Jose Luis, firts of all very thanks for your help making this huion drivers, now the output in the console was this:

```
--------------------------------------------------------------------------------
    |           Manufacturer: HUION???
    |                Product: PenTablet?
 64 |        Params block #1: ??????
    |                          Max X: 40000
    |                          Max Y: 25000
    |                   Max pressure: 2047
    |                     Resolution: 4000
    |
 79 |         Internal model: HA60?????
 7b |         Buttons status: HK On
 c8 |        Params block #2: HVAN?
    |                          Max X: 5636168
    |                          Max Y: 16640
    |                   Max pressure: 78
    |                     Resolution: 0
    |
 c9 |      Unknown string #1: HVAN?
 ca |  Internal manufacturer: HVAN?
--------------------------------------------------------------------------------
```

**Comment by partty** [comment]
Hi,
I'm interested in support for this tablet too.
My output is exactly the same.
I tried to add the tablet in the config myself, but I'm getting a "IndexError: array index out of range"
```
Traceback (most recent call last):
  File "./huion-tablet-driver.py", line 476, in <module>
    main.run()
  File "./huion-tablet-driver.py", line 32, in run
    main_loop()
  File "./huion-tablet-driver.py", line 268, in main_loop
    X = (data[8] << 16) + (data[3] << 8) + data[2]
IndexError: array index out of range
```
My config for the tablet is this:
```
[tablet_1060proplus]
model_name    = 1060PRO+
screen_width  = 1920
screen_height = 1080
pen_max_x     = 40000
pen_max_y     = 25000
pen_max_z     = 2047
resolution    = 4000
buttons       = 12
scrollbar     = 0
screen        = false
```

**Comment by joseluis** [comment]
Hi @LHT-01 & @partty , I've updated the script, adding a new debug mode to get better debugging information.

Please try the new version after changing `debug_mode = true` in the config file, and paste back some of the lines that appear when you use the pen, like the following:

```
data[12] = array('B', [8, 128, 17, 88, 33, 145, 0, 0, 0, 0, 0, 0])
{'TYPE': 128, 'X': '[8]<<16+[3]<<8+[2]=22545', 'Y': '[5]<<8+[4]=37153', 'PRESS': '[7]<<8+[6]=0'}
data[12] = array('B', [8, 129, 26, 88, 184, 145, 250, 1, 0, 0, 0, 0])
{'TYPE': 129, 'X': '[8]<<16+[3]<<8+[2]=22554', 'Y': '[5]<<8+[4]=37304', 'PRESS': '[7]<<8+[6]=506'}
data[12] = array('B', [8, 129, 21, 88, 54, 146, 123, 6, 0, 0, 0, 0])
{'TYPE': 129, 'X': '[8]<<16+[3]<<8+[2]=22549', 'Y': '[5]<<8+[4]=37430', 'PRESS': '[7]<<8+[6]=1659'}
data[12] = array('B', [8, 129, 6, 88, 135, 146, 192, 10, 0, 0, 0, 0])
{'TYPE': 129, 'X': '[8]<<16+[3]<<8+[2]=22534', 'Y': '[5]<<8+[4]=37511', 'PRESS': '[7]<<8+[6]=2752'}
```

**Comment by joseluis** [comment]
This tablet should be [supported by the latest digimend drivers](http://digimend.github.io/tablets/Huion_New_1060_Plus/) and work out of the box with them, so I'm gonna close the issue. Feel free to reopen it if any of you want to keep debugging it with my driver.
